<?php
/*********************************************************************************
 * The contents of this file are subject to the SugarCRM Master Subscription
 * Agreement ("License") which can be viewed at
 * http://www.sugarcrm.com/crm/master-subscription-agreement
 * By installing or using this file, You have unconditionally agreed to the
 * terms and conditions of the License, and You may not use this file except in
 * compliance with the License.  Under the terms of the license, You shall not,
 * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
 * or otherwise transfer Your rights to the Software, and 2) use the Software
 * for timesharing or service bureau purposes such as hosting the Software for
 * commercial gain and/or for the benefit of a third party.  Use of the Software
 * may be subject to applicable fees and any use of the Software without first
 * paying applicable fees is strictly prohibited.  You do not have the right to
 * remove SugarCRM copyrights from the source code or user interface.
 *
 * All copies of the Covered Code must include on each user interface screen:
 *  (i) the "Powered by SugarCRM" logo and
 *  (ii) the SugarCRM copyright notice
 * in the same form as they appear in the distribution.  See full license for
 * requirements.
 *
 * Your Warranty, Limitations of liability and Indemnity are expressly stated
 * in the License.  Please refer to the License for the specific language
 * governing these rights and limitations under the License.  Portions created
 * by SugarCRM are Copyright (C) 2004-2012 SugarCRM, Inc.; All Rights Reserved.
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'PRO',
    ),
  ),
  'readme' => '',
  'key' => 'ee',
  'author' => 'JF',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'EEimplementacion',
  'published_date' => '2012-03-22 09:05:43',
  'type' => 'module',
  'version' => 1332407144,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'EEimplementacion',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'ee_EjecucionPrograma',
      'class' => 'ee_EjecucionPrograma',
      'path' => 'modules/ee_EjecucionPrograma/ee_EjecucionPrograma.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'ee_Items',
      'class' => 'ee_Items',
      'path' => 'modules/ee_Items/ee_Items.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'ee_Logistica',
      'class' => 'ee_Logistica',
      'path' => 'modules/ee_Logistica/ee_Logistica.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ee_ejecucionprograma_ee_logistica_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ee_ejecucionprograma_ee_participantes_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ee_ejecucionprograma_activities_calls_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ee_ejecucionprograma_notes_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ee_ejecucionprograma_ee_logisticaMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ee_ejecucionprograma_ee_participantesMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ee_ejecucionprograma_activities_callsMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ee_ejecucionprograma_activities_meetingsMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ee_ejecucionprograma_activities_notesMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ee_ejecucionprograma_activities_tasksMetaData.php',
    ),
    6 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ee_ejecucionprograma_activities_emailsMetaData.php',
    ),
    7 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ee_ejecucionprograma_notesMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ee_EjecucionPrograma',
      'to' => 'modules/ee_EjecucionPrograma',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ee_Items',
      'to' => 'modules/ee_Items',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ee_Logistica',
      'to' => 'modules/ee_Logistica',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'bg_BG',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'cs_CZ',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'da_DK',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'de_DE',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'es_ES',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'et_EE',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'fr_FR',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'he_IL',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'hu_HU',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'it_it',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'lt_LT',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'ja_JP',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'nb_NO',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'nl_NL',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'pl_PL',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'pt_PT',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'ro_RO',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'ru_RU',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'sv_SE',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'tr_TR',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'zh_CN',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'pt_br',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'ca_ES',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'en_UK',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Logistica.php',
      'to_module' => 'ee_Logistica',
      'language' => 'sr_RS',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_us',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'bg_BG',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'cs_CZ',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'da_DK',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'de_DE',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'es_ES',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'et_EE',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'fr_FR',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'he_IL',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'hu_HU',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'it_it',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'lt_LT',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ja_JP',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nb_NO',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nl_NL',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pl_PL',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_PT',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ro_RO',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ru_RU',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sv_SE',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'tr_TR',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'zh_CN',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_br',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ca_ES',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_UK',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sr_RS',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'en_us',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'bg_BG',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'cs_CZ',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'da_DK',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'de_DE',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'es_ES',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'et_EE',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'fr_FR',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'he_IL',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'hu_HU',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'it_it',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'lt_LT',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'ja_JP',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'nb_NO',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'nl_NL',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'pl_PL',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'pt_PT',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'ro_RO',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'ru_RU',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'sv_SE',
    ),
    72 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'tr_TR',
    ),
    73 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'zh_CN',
    ),
    74 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'pt_br',
    ),
    75 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'ca_ES',
    ),
    76 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'en_UK',
    ),
    77 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Participantes.php',
      'to_module' => 'ee_Participantes',
      'language' => 'sr_RS',
    ),
    78 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_us',
    ),
    79 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'bg_BG',
    ),
    80 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'cs_CZ',
    ),
    81 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'da_DK',
    ),
    82 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'de_DE',
    ),
    83 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'es_ES',
    ),
    84 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'et_EE',
    ),
    85 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'fr_FR',
    ),
    86 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'he_IL',
    ),
    87 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'hu_HU',
    ),
    88 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'it_it',
    ),
    89 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'lt_LT',
    ),
    90 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ja_JP',
    ),
    91 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nb_NO',
    ),
    92 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nl_NL',
    ),
    93 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pl_PL',
    ),
    94 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_PT',
    ),
    95 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ro_RO',
    ),
    96 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ru_RU',
    ),
    97 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sv_SE',
    ),
    98 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'tr_TR',
    ),
    99 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'zh_CN',
    ),
    100 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_br',
    ),
    101 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ca_ES',
    ),
    102 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_UK',
    ),
    103 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sr_RS',
    ),
    104 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    105 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'bg_BG',
    ),
    106 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'cs_CZ',
    ),
    107 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'da_DK',
    ),
    108 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'de_DE',
    ),
    109 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    110 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'et_EE',
    ),
    111 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'fr_FR',
    ),
    112 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'he_IL',
    ),
    113 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'hu_HU',
    ),
    114 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'it_it',
    ),
    115 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'lt_LT',
    ),
    116 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'ja_JP',
    ),
    117 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'nb_NO',
    ),
    118 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'nl_NL',
    ),
    119 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'pl_PL',
    ),
    120 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'pt_PT',
    ),
    121 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'ro_RO',
    ),
    122 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'ru_RU',
    ),
    123 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'sv_SE',
    ),
    124 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'tr_TR',
    ),
    125 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'zh_CN',
    ),
    126 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'pt_br',
    ),
    127 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'ca_ES',
    ),
    128 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'en_UK',
    ),
    129 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'sr_RS',
    ),
    130 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_us',
    ),
    131 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'bg_BG',
    ),
    132 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'cs_CZ',
    ),
    133 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'da_DK',
    ),
    134 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'de_DE',
    ),
    135 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'es_ES',
    ),
    136 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'et_EE',
    ),
    137 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'fr_FR',
    ),
    138 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'he_IL',
    ),
    139 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'hu_HU',
    ),
    140 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'it_it',
    ),
    141 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'lt_LT',
    ),
    142 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ja_JP',
    ),
    143 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nb_NO',
    ),
    144 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nl_NL',
    ),
    145 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pl_PL',
    ),
    146 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_PT',
    ),
    147 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ro_RO',
    ),
    148 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ru_RU',
    ),
    149 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sv_SE',
    ),
    150 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'tr_TR',
    ),
    151 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'zh_CN',
    ),
    152 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_br',
    ),
    153 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ca_ES',
    ),
    154 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_UK',
    ),
    155 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sr_RS',
    ),
    156 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_us',
    ),
    157 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'bg_BG',
    ),
    158 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'cs_CZ',
    ),
    159 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'da_DK',
    ),
    160 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'de_DE',
    ),
    161 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'es_ES',
    ),
    162 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'et_EE',
    ),
    163 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'fr_FR',
    ),
    164 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'he_IL',
    ),
    165 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'hu_HU',
    ),
    166 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'it_it',
    ),
    167 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'lt_LT',
    ),
    168 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ja_JP',
    ),
    169 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nb_NO',
    ),
    170 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nl_NL',
    ),
    171 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pl_PL',
    ),
    172 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_PT',
    ),
    173 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ro_RO',
    ),
    174 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ru_RU',
    ),
    175 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sv_SE',
    ),
    176 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'tr_TR',
    ),
    177 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'zh_CN',
    ),
    178 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_br',
    ),
    179 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ca_ES',
    ),
    180 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_UK',
    ),
    181 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sr_RS',
    ),
    182 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_us',
    ),
    183 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'bg_BG',
    ),
    184 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'cs_CZ',
    ),
    185 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'da_DK',
    ),
    186 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'de_DE',
    ),
    187 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'es_ES',
    ),
    188 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'et_EE',
    ),
    189 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'fr_FR',
    ),
    190 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'he_IL',
    ),
    191 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'hu_HU',
    ),
    192 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'it_it',
    ),
    193 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'lt_LT',
    ),
    194 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ja_JP',
    ),
    195 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nb_NO',
    ),
    196 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nl_NL',
    ),
    197 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pl_PL',
    ),
    198 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_PT',
    ),
    199 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ro_RO',
    ),
    200 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ru_RU',
    ),
    201 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sv_SE',
    ),
    202 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'tr_TR',
    ),
    203 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'zh_CN',
    ),
    204 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_br',
    ),
    205 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ca_ES',
    ),
    206 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_UK',
    ),
    207 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sr_RS',
    ),
    208 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_us',
    ),
    209 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'bg_BG',
    ),
    210 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'cs_CZ',
    ),
    211 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'da_DK',
    ),
    212 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'de_DE',
    ),
    213 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'es_ES',
    ),
    214 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'et_EE',
    ),
    215 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'fr_FR',
    ),
    216 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'he_IL',
    ),
    217 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'hu_HU',
    ),
    218 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'it_it',
    ),
    219 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'lt_LT',
    ),
    220 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ja_JP',
    ),
    221 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nb_NO',
    ),
    222 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nl_NL',
    ),
    223 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pl_PL',
    ),
    224 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_PT',
    ),
    225 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ro_RO',
    ),
    226 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ru_RU',
    ),
    227 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sv_SE',
    ),
    228 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'tr_TR',
    ),
    229 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'zh_CN',
    ),
    230 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_br',
    ),
    231 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ca_ES',
    ),
    232 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_UK',
    ),
    233 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sr_RS',
    ),
    234 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_us',
    ),
    235 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'bg_BG',
    ),
    236 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'cs_CZ',
    ),
    237 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'da_DK',
    ),
    238 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'de_DE',
    ),
    239 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'es_ES',
    ),
    240 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'et_EE',
    ),
    241 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'fr_FR',
    ),
    242 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'he_IL',
    ),
    243 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'hu_HU',
    ),
    244 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'it_it',
    ),
    245 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'lt_LT',
    ),
    246 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ja_JP',
    ),
    247 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nb_NO',
    ),
    248 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nl_NL',
    ),
    249 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pl_PL',
    ),
    250 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_PT',
    ),
    251 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ro_RO',
    ),
    252 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ru_RU',
    ),
    253 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sv_SE',
    ),
    254 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'tr_TR',
    ),
    255 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'zh_CN',
    ),
    256 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_br',
    ),
    257 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ca_ES',
    ),
    258 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_UK',
    ),
    259 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sr_RS',
    ),
    260 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'en_us',
    ),
    261 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'bg_BG',
    ),
    262 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'cs_CZ',
    ),
    263 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'da_DK',
    ),
    264 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'de_DE',
    ),
    265 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'es_ES',
    ),
    266 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'et_EE',
    ),
    267 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'fr_FR',
    ),
    268 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'he_IL',
    ),
    269 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'hu_HU',
    ),
    270 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'it_it',
    ),
    271 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'lt_LT',
    ),
    272 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'ja_JP',
    ),
    273 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'nb_NO',
    ),
    274 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'nl_NL',
    ),
    275 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'pl_PL',
    ),
    276 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'pt_PT',
    ),
    277 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'ro_RO',
    ),
    278 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'ru_RU',
    ),
    279 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'sv_SE',
    ),
    280 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'tr_TR',
    ),
    281 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'zh_CN',
    ),
    282 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'pt_br',
    ),
    283 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'ca_ES',
    ),
    284 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'en_UK',
    ),
    285 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'sr_RS',
    ),
    286 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_us',
    ),
    287 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'bg_BG',
    ),
    288 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'cs_CZ',
    ),
    289 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'da_DK',
    ),
    290 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'de_DE',
    ),
    291 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'es_ES',
    ),
    292 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'et_EE',
    ),
    293 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'fr_FR',
    ),
    294 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'he_IL',
    ),
    295 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'hu_HU',
    ),
    296 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'it_it',
    ),
    297 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'lt_LT',
    ),
    298 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ja_JP',
    ),
    299 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nb_NO',
    ),
    300 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'nl_NL',
    ),
    301 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pl_PL',
    ),
    302 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_PT',
    ),
    303 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ro_RO',
    ),
    304 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ru_RU',
    ),
    305 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sv_SE',
    ),
    306 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'tr_TR',
    ),
    307 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'zh_CN',
    ),
    308 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'pt_br',
    ),
    309 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'ca_ES',
    ),
    310 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'en_UK',
    ),
    311 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
      'language' => 'sr_RS',
    ),
    312 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    313 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_ee_logistica_ee_Logistica.php',
      'to_module' => 'ee_Logistica',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_ee_logistica_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_ee_participantes_ee_Participantes.php',
      'to_module' => 'ee_Participantes',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_ee_participantes_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_activities_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_activities_calls_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_activities_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_activities_meetings_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_activities_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_activities_notes_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_activities_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_activities_tasks_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_activities_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_activities_emails_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_ejecucionprograma_notes_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'ee_ejecucionprograma_activities_calls_name',
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'ee_ejecucionprograma_activities_meetings_name',
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'ee_ejecucionprograma_activities_notes_name',
      ),
    ),
    5 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'ee_ejecucionprograma_activities_tasks_name',
      ),
    ),
    6 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    7 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'ee_ejecucionprograma_notes_name',
      ),
    ),
  ),
  'wireless_subpanels' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/ee_ejecucionprograma_ee_logistica_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/ee_ejecucionprograma_ee_participantes_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/ee_ejecucionprograma_activities_calls_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/ee_ejecucionprograma_activities_meetings_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/ee_ejecucionprograma_activities_notes_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/ee_ejecucionprograma_activities_tasks_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/ee_ejecucionprograma_activities_emails_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/ee_ejecucionprograma_notes_ee_EjecucionPrograma.php',
      'to_module' => 'ee_EjecucionPrograma',
    ),
  ),
);