<?php
/*********************************************************************************
 * The contents of this file are subject to the SugarCRM Master Subscription
 * Agreement ("License") which can be viewed at
 * http://www.sugarcrm.com/crm/master-subscription-agreement
 * By installing or using this file, You have unconditionally agreed to the
 * terms and conditions of the License, and You may not use this file except in
 * compliance with the License.  Under the terms of the license, You shall not,
 * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
 * or otherwise transfer Your rights to the Software, and 2) use the Software
 * for timesharing or service bureau purposes such as hosting the Software for
 * commercial gain and/or for the benefit of a third party.  Use of the Software
 * may be subject to applicable fees and any use of the Software without first
 * paying applicable fees is strictly prohibited.  You do not have the right to
 * remove SugarCRM copyrights from the source code or user interface.
 *
 * All copies of the Covered Code must include on each user interface screen:
 *  (i) the "Powered by SugarCRM" logo and
 *  (ii) the SugarCRM copyright notice
 * in the same form as they appear in the distribution.  See full license for
 * requirements.
 *
 * Your Warranty, Limitations of liability and Indemnity are expressly stated
 * in the License.  Please refer to the License for the specific language
 * governing these rights and limitations under the License.  Portions created
 * by SugarCRM are Copyright (C) 2004-2012 SugarCRM, Inc.; All Rights Reserved.
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'PRO',
    ),
  ),
  'readme' => '',
  'key' => 'ee',
  'author' => 'Jose Sambrano',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Provincia',
  'published_date' => '2012-03-22 09:14:57',
  'type' => 'module',
  'version' => 1332407697,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Provincia',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'ee_Provincia',
      'class' => 'ee_Provincia',
      'path' => 'modules/ee_Provincia/ee_Provincia.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ee_provincia_ee_ciudad_ee_Provincia.php',
      'to_module' => 'ee_Provincia',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ee_provincia_ee_ciudadMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ee_Provincia',
      'to' => 'modules/ee_Provincia',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'bg_BG',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'cs_CZ',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'da_DK',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'de_DE',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'es_ES',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'et_EE',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'fr_FR',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'he_IL',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'hu_HU',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'it_it',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'lt_LT',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'ja_JP',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'nb_NO',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'nl_NL',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'pl_PL',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'pt_PT',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'ro_RO',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'ru_RU',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'sv_SE',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'tr_TR',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'zh_CN',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'pt_br',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'ca_ES',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'en_UK',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
      'language' => 'sr_RS',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'en_us',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'bg_BG',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'cs_CZ',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'da_DK',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'de_DE',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'es_ES',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'et_EE',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'fr_FR',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'he_IL',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'hu_HU',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'it_it',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'lt_LT',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'ja_JP',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'nb_NO',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'nl_NL',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'pl_PL',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'pt_PT',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'ro_RO',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'ru_RU',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'sv_SE',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'tr_TR',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'zh_CN',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'pt_br',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'ca_ES',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'en_UK',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ee_Provincia.php',
      'to_module' => 'ee_Provincia',
      'language' => 'sr_RS',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_provincia_ee_ciudad_ee_Ciudad.php',
      'to_module' => 'ee_Ciudad',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ee_provincia_ee_ciudad_ee_Provincia.php',
      'to_module' => 'ee_Provincia',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
        'ee_Ciudad' => 'ee_provincia_ee_ciudad_name',
      ),
    ),
  ),
  'wireless_subpanels' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/ee_provincia_ee_ciudad_ee_Provincia.php',
      'to_module' => 'ee_Provincia',
    ),
  ),
);